### ISSUE TITLE
[Question] Is it possible to use the CommunityToolkit with Uno.WinUI?

### ISSUE THREAD

**Issue by vadd98** [unoplatform/Uno.WindowsCommunityToolkit#128]
I'm developing a WinUI 3 app and on Windows there is already a preview for the CommunityToolkit targeting the WinUI 3.
I'd like to know if your porting of the CommunityToolkit can be used with Uno.WinUI or if I need to wait for a specific version

**Comment by jeromelaban** [comment]
Thanks for the feedback. At this point, it's not possible to use the Uno fork of the Windows Community Toolkit in Uno.WinUI. 

We're following closely what the WCT team will do to support this.

**Comment by SkyeHoefling** [comment]
I have been doing some experimenting with the latest stable bits of Uno Platform (WinUI3) and Windows App SDK (Project Reunion). It looks like the WCT team have released a set of NuGets for WinUI named [NuGet Packages: CommunityToolkit.WinUI.*](https://www.nuget.org/packages?q=CommunityToolkit.WinUI). All of these NuGet Packages depend on Project Reunion and WinUI as far as I can tell. 

@jeromelaban are we still waiting to see how they support it or is there something that we can start doing in this project to add support?

**Comment by jeromelaban** [comment]
We're going to be adding support once we figure out a way to work with the branch that was created specifically for supporting WinUI 3.

**Comment by Evengard** [comment]
Any news on this one?

**Comment by jeromelaban** [comment]
It's been implemented a while ago. The documentation at the front page explains how to do this: https://github.com/unoplatform/Uno.WindowsCommunityToolkit. [as well as the Uno Docs](https://platform.uno/docs/articles/uno-community-toolkit.html?tabs=tabid-winui).

<blockquote><img src="https://opengraph.githubassets.com/13a9d3a94a32aafc57983f3279c0de71303b9f1bc6b65899f6e33a454c154d61/unoplatform/Uno.WindowsCommunityToolkit" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/unoplatform/Uno.WindowsCommunityToolkit">GitHub - unoplatform/Uno.WindowsCommunityToolkit: The Windows Community Toolkit is a collection of helper functions, custom controls, and app services. It simplifies and demonstrates common developer tasks building UWP apps for Windows 10. The toolkit is part of the .NET Foundation.</a></strong></div><div>The Windows Community Toolkit is a collection of helper functions, custom controls, and app services. It simplifies and demonstrates common developer tasks building UWP apps for Windows 10. The too...</div></blockquote>

**Comment by Evengard** [comment]
Oh, I missed this somehow. Thanks for the update!
