### ISSUE TITLE
[Android] Java.Lang.NoClassDefFoundError: 'Failed resolution of: Landroidx/arch/core/executor/ArchTaskExecutor;'

### ISSUE THREAD

**Issue by workgroupengineering** [unoplatform/Uno.WindowsCommunityToolkit#132]
## Describe the bug
When run app throwed Java.Lang.NoClassDefFoundError

- [ ] Is this bug a regression in the toolkit?  If so, what toolkit version did you last see it work:

## Steps to Reproduce

- [ ] Can this be reproduced in the Sample App? (Either in a sample as-is or with new XAML pasted in the editor.) If so, please provide custom XAML or steps to reproduce. If not, let us know why it can't be reproduced (e.g. more complex setup, environment, dependencies, etc...) 

1. Create new app using uno template on visual studio
2. update Uno Platform at last prerelase
3. install Uno.Microsoft.Toolkit.Uwp.UI.Controls 
4. Run
5. See error

## Expected behavior
error do not throw

## Environment

```
NuGet Package(s):  
 - Uno.U" 3.6.0-dev.478
 - Uno.UI.RemoteControl  3.6.0-dev.478
 - Uno.UniversalImageLoader 1.9.33
 - Microsoft.Extensions.Logging.Console 1.1.1
 - Microsoft.Extensions.Logging.Filter 1.1.1

Package Version(s): 
Uno.Microsoft.Toolkit.Uwp.UI.Controls 6.0.0.ge975abb046

Device form factor:
- [ ] Windows
- [ ] macOS
- [ ] iOS
- [x] Android (Oreo 8.1)
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms

Visual Studio 
- [ ] 2017 (version: )
- [x] 2019 (version: 18.9.1 ) 
- [ ] 2019 Preview (version: )

```

## Additional context
if remove Uno.Microsoft.Toolkit.Uwp.UI.Controls work

## Workaraund
```xml
<PackageReference Include="Xamarin.AndroidX.Arch.Core.Runtime" Version="2.1.0.8" />
```

**Comment by jeromelaban** [comment]
Fixed by unoplatform/uno#5501
