### ISSUE TITLE
[Feature] Unsigned assembiles?

### ISSUE THREAD

**Issue by trungnt2910** [unoplatform/Uno.WindowsCommunityToolkit#155]
## Describe the problem this feature would solve

I'm using .NET Framework a Uno Platform application, that uses the `DataGrid` control. However, the application always crashes when initializing the `DataGrid` as `Uno.UI` is not strongly-named (`a strongly-named assembly is required. (Exception from HRESULT: 0x80131044)`. 

## Describe the solution

Either:
- Strongly Name Uno Platform assemblies (which Jérôme Laban said you [won't](https://github.com/unoplatform/uno/issues/4865#issuecomment-757538110))?
- Release special unsigned builds for use with .NET Framework WPF applications.

## Describe alternatives you've considered

Currently I'm cloning your source code and directly reference the project but it's a maintenance burden compared to nuget packages.

**Comment by jeromelaban** [comment]
Thanks for the report!

We will not change our stance on signing assemblies, as it causes more trouble than it saves. .NET framework support is not something we aim for, as .NET 5+ is supported in Windows 7, the oldest target we support.
