### ISSUE TITLE
HamburgerMenu doesn't work on Droid (bombs app).

### ISSUE THREAD

**Issue by JimGaleForce** [unoplatform/Uno.WindowsCommunityToolkit#16]
## I'm submitting a...

Bug report (I searched for similar issues and did not find one)

## Current behavior
UWP HamburgerMenu works (from Microsoft.Toolkit...). However, Droid + Uno.Microsoft.Toolkit, compiles, deploys, but bombs immediately on display of the xaml. (logcat cannot connect). Without the HamburgerMenu, the app functions.

## Expected behavior
function with HamburgerMenu

## Minimal reproduction of the problem with instructions
```xaml
    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        <controls:HamburgerMenu></controls:HamburgerMenu>

        <TextBlock Text="Hello, world !" Margin="20" FontSize="30" />
    </Grid>
```

## Environment

```
Nuget Package(s): 
Uno.Microsoft.Toolkit.Uwp.UI
Uno.Microsoft.Toolkit.Uwp.UI.Controls

Package Version(s): 

Windows 10 Build Number:
- [ ] Insider Build (build number: 17134)

Visual Studio 
15.8.2

```

**Comment by jeromelaban** [comment]
Thanks for the report! The Android head is not present in the samples, which is why this has been overlooked. We'll need to at this one for the testing.

**Comment by JimGaleForce** [comment]
Sorry, nevermind this, my fault. I forgot to turn off "Use Shared Runtime" again.
(for anyone else, Properties->Android Options->Packaging properties->[ ]Use Shared Runtime needs to be unchecked as there are no other runtimes on the device to share). [this happens will most controls, not just this one].

**Comment by jeromelaban** [comment]
Still is an interesting one... @jonathanpeppers you were recently looking for unusual uses of configuration flags, this is one.

**Comment by jonathanpeppers** [comment]
> Properties->Android Options->Packaging properties->[ ]Use Shared Runtime needs to be unchecked

Ah! no! If there is a bug here, we should fix it. You should _never_ have to do this... Your build times will get slower...

@JimGaleForce can you give some more detail on what the error message was? Can you get [diagnostic build logs](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output) if it happens again?

**Comment by jonathanpeppers** [comment]
@JimGaleForce file a bug here, and mention me if you get more info: https://github.com/xamarin/xamarin-android/issues
