### ISSUE TITLE
Add .NET 6 Mobile support

### ISSUE THREAD

**Issue by xperiandri** [unoplatform/Uno.WindowsCommunityToolkit#173]
## Describe the bug

![Screenshot 2022-03-07 at 18 38 11](https://user-images.githubusercontent.com/2365592/157116227-7b7251de-1110-4902-8177-f77148002274.png)
![Screenshot 2022-03-07 at 19 17 50](https://user-images.githubusercontent.com/2365592/157116245-6db51faa-e309-48df-a739-bc5b9c05b5cd.png)

## Steps to Reproduce

1. Create app from .NET 6 template
2. Update `Uno.UI` to 4.2.0-dev.223
3. Reference `Uno.Microsoft.Toolkit.Uwp.UI.Controls` 7.1.*
4. Run on iOS Simulator from Mac device

## Expected behavior

Runs without exception

## Environment

NuGet Package(s): 
`Uno.UI` 4.2.0-dev.223
`Uno.Microsoft.Toolkit.Uwp.UI.Controls` 7.1.11

App min and target version:

- May 2019 Update (18362)

Device form factor:
- iOS

Visual Studio for Mac 2022 version:

7.0.7303

## Additional context

Run on macOS, MAUI Preview 13.7

**Comment by francoistanguay** [comment]
Available through a number of packages, including https://www.nuget.org/packages/Uno.CommunityToolkit.WinUI.UI.Controls


<blockquote><img src="https://api.nuget.org/v3-flatcontainer/uno.communitytoolkit.winui.ui.controls/7.1.100/icon" width="48" align="right"><div><strong><a href="https://nuget.org/packages/Uno.CommunityToolkit.WinUI.UI.Controls/">Uno.CommunityToolkit.WinUI.UI.Controls 7.1.100</a></strong></div><div>This library provides Controls, Panels, ItemsRepeater Layouts, and various other classes & helpers for XAML UI development with UWP. It is a part of the Windows Community Toolkit.

      This package is only an aggregate of its dependencies, meaning it's a meta-package and has no assemblies. You can find out how to optimize your app after development at https://aka.ms/wct/optimize</div></blockquote>
