### ISSUE TITLE
ColorPicker has issues on WASM

### ISSUE THREAD

**Issue by hawkerm** [unoplatform/Uno.WindowsCommunityToolkit#190]
## Describe the bug

Couple of issues with the display of the ColorPicker on WASM (not sure if only when displayed in ColorPickerButton)

1. Color Palette grid doesn't display.
2. Sliders don't display until manipulated:

![image](https://user-images.githubusercontent.com/8959496/210499776-5aebb4ab-2aa3-429b-a1a5-7cb7731e6556.png)

![image](https://user-images.githubusercontent.com/8959496/210499805-af9c88b8-0e73-4518-b580-ec7613dae985.png)

Didn't test the square picker tab (had it disabled in my scenario).

## Steps to Reproduce

```xml
                          <controls:ColorPickerButton>
                            <controls:ColorPickerButton.ColorPickerStyle>
                                <Style TargetType="controls:ColorPicker">
                                    <Setter Property="IsAlphaEnabled" Value="False" />
                                    <Setter Property="IsColorSpectrumVisible" Value="False" />
                                    <Setter Property="IsColorPaletteVisible" Value="True" />
                                    <Setter Property="IsColorChannelTextInputVisible" Value="True" />
                                </Style>
                            </controls:ColorPickerButton.ColorPickerStyle>
                        </controls:ColorPickerButton>
```

## Expected behavior

Able to see Palette color grid:

![image](https://user-images.githubusercontent.com/8959496/210500101-ff69381b-623c-4e30-b072-4923f9480072.png)

## Environment

NuGet Package(s): Uno.Microsoft.Toolkit.Uwp.UI.Controls.Input 7.1.11

Package Version(s):

Windows 10 Build Number:

- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [ ] May 2020 Update (19041)
- [ ] Insider Build ({build_number})

App min and target version:

- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [ ] May 2020 Update (19041)
- [ ] Insider Build ({build_number})

Device form factor:
- [ ] Windows
- [ ] macOS
- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms

Visual Studio version:

- [ ] 2017 (15.{minor_version})
- [ ] 2019 (16.{minor_version})
- [x] 2022 (17.{minor_version})

**Comment by jeromelaban** [comment]
Thanks for the report! Let's continue the tracking here: https://github.com/unoplatform/uno/issues/6834
