### ISSUE TITLE
MasterDetailsView selection not working

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/Uno.WindowsCommunityToolkit#96]
## Describe the bug

- [x] Is this bug a regression in the toolkit?  If so, what toolkit version did you last see it work: 6.1.0-build.71.g38c59ea2a0

## Steps to Reproduce
1. Use `MasterDetailsView`, bind some items
2. Click on an item and observe the view does not change to the details view

## Expected behavior

Details of the item hso

## Environment

```
NuGet Package(s): 

Package Version(s): 

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [ ] Insider Build (build number: )

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [ ] Insider Build (xxxxx)

Device form factor:
- [ ] Desktop
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [ ] 2017 (version: )
- [ ] 2019 (version: ) 
- [ ] 2019 Preview (version: )

```

**Comment by MartinZikmund** [comment]
I will take a look at this

**Comment by MartinZikmund** [comment]
@davidjohnoliver I have discovered that the selected item is set as the following in the generated code is called:

```
private static void SetSelectedItem(object instance, object value, Windows.UI.Xaml.DependencyPropertyValuePrecedences? precedence) => Windows.UI.Xaml.DependencyObjectExtensions.SetValue(instance, global::Microsoft.Toolkit.Uwp.UI.Controls.MasterDetailsView.SelectedItemProperty, value, precedence);
```

Where `value` is the selected item and `precedence` is Local. However, the value is still not applied, so far I can't figure out why.

**Comment by MartinZikmund** [comment]
Is there an easy way to debug WCT against local Uno source code? I would need to step into the `SetValue` method to see what is happening

**Comment by jeromelaban** [comment]
You would debug it the same way you would using a local cache override of the Uno version used by the head you're debugging: https://github.com/unoplatform/uno/blob/e1448bc79daf6da0fc246e861e3d5f90c89791b7/src/crosstargeting_override.props.sample#L46

<blockquote><img src="https://repository-images.githubusercontent.com/132453438/7fcbaf80-9f86-11e9-9d5c-1feea63c9a2e" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/unoplatform/uno">unoplatform/uno</a></strong></div><div>Build Mobile, Desktop and WebAssembly apps with C# and XAML. Today. Open source and professionally supported. - unoplatform/uno</div></blockquote>

**Comment by MartinZikmund** [comment]
@jeromelaban Oh, I haven't used that yet. I have set the override, rebuilt Uno.UI and then run WCT Sample app on Android, how do I now step into the Uno.UI source, please?

**Comment by jeromelaban** [comment]
Stepping in should work right away, either by opening a file from the Uno.UI solution inside your debugging solution, or by stepping into an Uno method from your solution's sources.

**Comment by MartinZikmund** [comment]
For some reason this does not function here 🤔 . But I added some logging at least, so I see the values in debug output. What I found out so far is that the `SelectedItem` value changes properly, with `Local` precedence, so it must be some issue with `RaiseCallbacks` which does not raise the `SelectedItem` property changed callback on `MasterDetailsView`. So far don't know what it could cause though.

**Comment by edparitor** [comment]
Hi @MartinZikmund. Any progress/workaround for this? I need to upgrade to uno.ui 3 to use Uno.Ui.MSAL, but my client is already using MasterDetailsView which stopped working in version 178, which is the only publicly released version of the toolkit that works with uno.ui 3.
